# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    # env_file: # wont read custom env_file at startup https://stackoverflow.com/a/64723777/6274120
    #   - database.env # configure postgres
    environment:
      - PGDATA
    ports: # the difference with 'expose' is that 'expose' is for the container, not the host
      - "5432:5432" 
    volumes:
      - db-data:${PGDATA} # persist data even if container shuts down
volumes:
  db-data: # named volumes can be managed easier using docker-compose